name: flame_game_jam_2025
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
    
  uuid: ^4.5.1
  path: ^1.9.1
  shared_preferences: ^2.5.2
  google_fonts: ^6.2.1
  flutter_native_splash: ^2.4.5
  wakelock_plus: ^1.2.10

  flame: ^1.28.1
  flame_audio: ^2.11.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  build_runner: ^2.4.15
  flutter_gen_runner: ^5.10.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/miner/
    - assets/images/furnace/
    - assets/images/rocketPad/
    - assets/images/rocket/
    - assets/images/turret/
    - assets/images/armory/
    - assets/images/ennemy/
    - assets/audio/music/
    - assets/audio/sfx/
    - assets/json/

  shaders:
    - assets/shaders/space_sky.frag
    - assets/shaders/night_sky.frag

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/app_icons/icon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/app_icons/icon.png"
    background_color: "#000000"
    theme_color: "#000000"
  windows:
    generate: true
    image_path: "assets/app_icons/icon.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/app_icons/icon.png"


flutter_native_splash:
  color: "#000000"
  image: assets/app_icons/splash.png

  android_12:
    color: "#000000"
    icon_background_color: "#000000"
    color_dark: "#000000"
    icon_background_color_dark: "#000000"